### ISSUE TITLE
Can't get it to run with global caddy and nginx setup

### ISSUE THREAD

**Issue by ryandikdan** [TeamPiped/Piped-Docker#45]
Hello, thanks for the awesome project. I'm trying to run it locally. I ran the configure-instance.sh and chose nginx. I added those urls to my Caddyfile and that redirect appears to work (I have many other reverse_proxies that work fine). When I check the docker logs for the piped instances, they all look fine, but the nginx is giving this error: 
```
2024/06/21 00:24:07 [emerg] 1#1: host not found in upstream "pipedfrontend:80" in /etc/nginx/conf.d/pipedfrontend.conf:2
nginx: [emerg] host not found in upstream "pipedfrontend:80" in /etc/nginx/conf.d/pipedfrontend.conf:2
```
I used the automatically generated compose file as below (with the `pipedfrontend` in nginx dependencies changed to `piped-frontend` so it'll work):
```
services:
    piped-frontend:
        image: 1337kavin/piped-frontend:latest
        restart: unless-stopped
        depends_on:
            - piped
        environment:
            BACKEND_HOSTNAME: pipedapi.test.info
        container_name: piped-frontend
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        environment:
            - UDS=1
        volumes:
            - piped-proxy:/app/socket
        container_name: piped-proxy
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        volumes:
            - ./config/config.properties:/app/config.properties:ro
        depends_on:
            - postgres
        container_name: piped-backend
    nginx:
        image: nginx:mainline-alpine
        restart: unless-stopped
        ports:
            - "9090:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf:ro
            - ./config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf:ro
            - ./config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf:ro
            - ./config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro
            - piped-proxy:/var/run/ytproxy
        container_name: nginx
        depends_on:
            - piped
            - piped-proxy
            - piped-frontend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.piped.rule=Host(`FRONTEND_HOSTNAME`, `BACKEND_HOSTNAME`, `PROXY_HOSTNAME`)"
            - "traefik.http.routers.piped.entrypoints=websecure"
            - "traefik.http.services.piped.loadbalancer.server.port=8080"
    postgres:
        image: postgres:15
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: postgres
    watchtower:
        image: containrrr/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/timezone:/etc/timezone:ro
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_INCLUDE_RESTARTING=true
        container_name: watchtower
        command: piped-frontend piped-backend piped-proxy varnish nginx postgres watchtower
volumes:
    piped-proxy: null
```
I changed the 8080 to 9090 since I'm using something on 8080 already.
Am I missing something? I tried adding ports to each of the piped packages, but it was recommended to put the same port for each piped instance, and it says that that port is already in use when I do and won't start up.

I'm running it on Ubuntu 22.04.4 LTS x86_64.
